apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pokemon-qa
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.example.yaml
  - postgres.yaml
  - backend.yaml
  - worker.yaml
  - frontend.yaml
  - ingress.yaml
